# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_lessons_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationslog',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
