# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-11 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_lessons_search', '0002_auto_20210411_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationslog',
            old_name='sessions',
            new_name='session',
        ),
    ]
