# Generated by Django 3.2 on 2021-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covered',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
