# Generated by Django 3.2 on 2021-04-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_covered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
